{
    # Learning rate
    "lr": 0.0001,
    # Size of images to be resized before training
    "image_size": 448,
    # Size of output embedding vector
    "embedding_size": 128,
    # Batch size
    "batch_size": 48,
    # Margin factor
    "margin": 0.1,
    # Scaling factor
    "alpha": 32,
    # Whether to use pretrained weight on ImageNet or not
    "pretrained": True,
}
