{
    # Learning rate
    "lr": 0.0001,
    # Size of images to be resized before training
    "image_size": 448,
    # Size of output embedding vector
    "embedding_size": 128,
    # Numbers of classes to sample in each batch
    "classes_per_batch": 12,
    # Number of samples per class to sample in each batch
    "samples_per_class": 4,
    # Margin for triplet loss
    "margin": 0.5,
    # sample "batch_hard_triplets" or "batch_hardest_triplets"
    "sampling_type": "batch_hard_triplets",
    # Whether to use pretrained weight on ImageNet or not
    "pretrained": True,
}
